/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteRouteImport } from './routes/_auth/dashboard/route'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthDashboardTeacherRouteRouteImport } from './routes/_auth/dashboard/teacher/route'
import { Route as AuthDashboardStudentRouteRouteImport } from './routes/_auth/dashboard/student/route'
import { Route as AuthDashboardGuestRouteRouteImport } from './routes/_auth/dashboard/guest/route'
import { Route as AuthDashboardAdminRouteRouteImport } from './routes/_auth/dashboard/admin/route'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRouteRoute = AuthDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardTeacherRouteRoute =
  AuthDashboardTeacherRouteRouteImport.update({
    id: '/teacher',
    path: '/teacher',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardStudentRouteRoute =
  AuthDashboardStudentRouteRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardGuestRouteRoute = AuthDashboardGuestRouteRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardAdminRouteRoute = AuthDashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/dashboard/admin': typeof AuthDashboardAdminRouteRoute
  '/dashboard/guest': typeof AuthDashboardGuestRouteRoute
  '/dashboard/student': typeof AuthDashboardStudentRouteRoute
  '/dashboard/teacher': typeof AuthDashboardTeacherRouteRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof AuthDashboardAdminRouteRoute
  '/dashboard/guest': typeof AuthDashboardGuestRouteRoute
  '/dashboard/student': typeof AuthDashboardStudentRouteRoute
  '/dashboard/teacher': typeof AuthDashboardTeacherRouteRoute
  '/dashboard': typeof AuthDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/_auth/dashboard/admin': typeof AuthDashboardAdminRouteRoute
  '/_auth/dashboard/guest': typeof AuthDashboardGuestRouteRoute
  '/_auth/dashboard/student': typeof AuthDashboardStudentRouteRoute
  '/_auth/dashboard/teacher': typeof AuthDashboardTeacherRouteRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/guest'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/guest'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard'
    | '/_auth/dashboard/admin'
    | '/_auth/dashboard/guest'
    | '/_auth/dashboard/student'
    | '/_auth/dashboard/teacher'
    | '/_auth/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/teacher': {
      id: '/_auth/dashboard/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof AuthDashboardTeacherRouteRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/student': {
      id: '/_auth/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthDashboardStudentRouteRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/guest': {
      id: '/_auth/dashboard/guest'
      path: '/guest'
      fullPath: '/dashboard/guest'
      preLoaderRoute: typeof AuthDashboardGuestRouteRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/admin': {
      id: '/_auth/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthDashboardAdminRouteRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
  }
}

interface AuthDashboardRouteRouteChildren {
  AuthDashboardAdminRouteRoute: typeof AuthDashboardAdminRouteRoute
  AuthDashboardGuestRouteRoute: typeof AuthDashboardGuestRouteRoute
  AuthDashboardStudentRouteRoute: typeof AuthDashboardStudentRouteRoute
  AuthDashboardTeacherRouteRoute: typeof AuthDashboardTeacherRouteRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
}

const AuthDashboardRouteRouteChildren: AuthDashboardRouteRouteChildren = {
  AuthDashboardAdminRouteRoute: AuthDashboardAdminRouteRoute,
  AuthDashboardGuestRouteRoute: AuthDashboardGuestRouteRoute,
  AuthDashboardStudentRouteRoute: AuthDashboardStudentRouteRoute,
  AuthDashboardTeacherRouteRoute: AuthDashboardTeacherRouteRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
}

const AuthDashboardRouteRouteWithChildren =
  AuthDashboardRouteRoute._addFileChildren(AuthDashboardRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthDashboardRouteRoute: typeof AuthDashboardRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRouteRoute: AuthDashboardRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
